baseurl: /

profile:
  name: David Charte
  alias: fdavidcl
  pic: https://secure.gravatar.com/avatar/7083d161b041964b75c38376d9dee37a?s=200
  github: fdavidcl
  blog: http://blog.fdavidcl.me
  twitter: fdavidcl
  linkedin: fdavidcl
  scholar: FRv_MwYAAAAJ

collections:
  - publications
  - projects
