baseurl: /

profile:
  name: Alejandro Charte
  alias: acharluk
  pic: assets/5154281.jpg
  github: acharluk
  blog: http://blog.acharluk.me
  player: acharluk
  youtube: acharluk
  twitter: acharluk

collections:
  - publications
  - projects
  - guides
