baseurl: /

profile:
  name: Alejandro Charte
  alias: acharluk
  pic: assets/logo.png
  github: acharluk
  blog: http://blog.acharluk.me
  player: acharluk
  twitter: acharluk

collections:
  - publications
  - projects
